### ISSUE TITLE
command dosen't work in terminal (Windows)

### ISSUE THREAD

**Issue by JaniSavolainen** [segmentio/create-next-app#1]
Have:
-windows 10
-node v7.9.0
-npm 4.5.0

### Description
create-next-app installs correctly and globally. when trying to run command i get following error "create-next-app' is not recognized as an internal or external command, operable program or batch file."

something to do with cmd PATH?

**Comment by fouad** [comment]
Hey @JaniSavolainen!

Do other global modules work for you?
Can you try [adding npm to your path](http://stackoverflow.com/a/30716060) or [installing/running as admin](http://stackoverflow.com/a/39373907)?

**Comment by JaniSavolainen** [comment]
Yes. Other global modules work well. Compared create-react-app but did not find the problem. Added manualy PATH to point "create-next-app.cmd". Now works well. Windows 10 uses C:\Users\*******\AppData\Roaming\npm by default. there i can find other global command. If helps a bit for fix.

**Comment by frankhale** [comment]
I have a slightly different issue on Windows 10, looks like a Cygwin type environment is assumed but I cannot find it mentioned in the docs. Trying to do `create-next-app foobar` yields this:

```
Creating foobar...

- Copying files{ Error: spawn cp ENOENT
    at notFoundError (C:\Users\frank\AppData\Roaming\npm\node_modules\create-next-app\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\frank\AppData\Roaming\npm\node_modules\create-next-app\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\frank\AppData\Roaming\npm\node_modules\create-next-app\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cp',
  killed: false,
  stdout: '',
  stderr: '\'cp\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n',
  failed: true,
  signal: null,
  cmd: 'cp -r C:\\Users\\frank\\AppData\\Roaming\\npm\\node_modules\\create-next-app\\lib\\templates\\default C:\\Users\\frank\\Desktop/foobar',
  timedOut: false }
> Error! Copy command failed, try again.
```

Definitely don't have a `cp` command in the Windows terminal. I'll install Cygwin and try again.

**Comment by frankhale** [comment]
Installing Cygwin was the key to make `create-next-app` work on my Windows 10 machine.

**Comment by codepunkt** [comment]
That's unfortunate. Please fix!

**Comment by frankhale** [comment]
@codepunkt yeah because create-react-app did not have the same requirements. Would be nice to not need Cygwin on a Windows machine!

**Comment by ricardo-devis-agullo** [comment]
Hi, I created a [PR](https://github.com/segmentio/create-next-app/pull/8) to fix that.

**Comment by fouad** [comment]
Thanks to @ricardo-devis-agullo for fixing this issue in #8, just merged & deploying a release
