### ISSUE TITLE
Error when running yarn dev for the first time

### ISSUE THREAD

**Issue by Miz85** [segmentio/create-next-app#14]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Can you reproduce the problem with latest npm?
yes

Many errors, especially related to "missing modules", are due to npm bugs.

If you're using Windows, [follow these instructions to update npm](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows).

If you're using OS X or Linux, run this to update npm:

```
npm install -g npm@latest

cd your_project_directory
rm -rf node_modules
npm install
```

Then try to reproduce the issue again.

Can you still reproduce it?
yes

### Description
When running `yarn dev` I get the following an error saying that the components Head and Nav don't match a file on disk due to wrong imports in the default template `index.js` file

I created the following PR: https://github.com/segmentio/create-next-app/pull/13 that fixes it.

**Comment by fouad** [comment]
closed by #13
