### ISSUE TITLE
koa exmaple support async

### ISSUE THREAD

**Issue by jason-ivy** [segmentio/create-next-app#15]
router.get('/a', async ctx => {
                   ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

**Comment by stephenmathieson** [comment]
what version of node are you using? it doesn't look like the server is transpiled there, so if your node version doesn't support async/await yet, it's not going to run properly.

fwiw on node 7.9, the example runs fine for me:

```
~/dev/src/github.com/segmentio/create-next-app on master ∴ node -v
v7.9.0
~/dev/src/github.com/segmentio/create-next-app on master ∴ ./bin/create-next-app --example custom-server-koa myapp
> Success! Downloaded custom-server-koa files for myapp

  Installing npm modules:
    react
    react-dom
    next

> Success! Installed dependencies for myapp

  Awesome! You're now ready to start coding.

  We already ran npm install for you, so your next steps are:

  $ cd myapp

  To build a version for production:

  $ npm run build

  To run the server in production:

  $ npm run start

  To start a local server for development:

  $ npm run dev

  Questions? Feedback? Please let us know!

  https://github.com/segmentio/create-next-app/issues

~/dev/src/github.com/segmentio/create-next-app on master [?] ∴ cd myapp/
~/dev/src/github.com/segmentio/create-next-app/myapp on master [?] ∴ npm run dev

> custom-server-koa@ dev /Users/stephenmathieson/dev/src/github.com/segmentio/create-next-app/myapp
> node server.js



 DONE  Compiled successfully in 4161ms

> Ready on http://localhost:3000
^C
~/dev/src/github.com/segmentio/create-next-app/myapp on master [?] ∴ 
```

**Comment by jason-ivy** [comment]
node 6,. I have already solved with babel, thanks
