### ISSUE TITLE
Creating extraneous node_modules/ & yarn.lock outside of designated projectDir.

### ISSUE THREAD

**Issue by rockchalkwushock** [segmentio/create-next-app#16]
### Description

When running:

```sh
Codys-Mac-mini:Desktop codybrunner$ create-next-app my-app
# populates /my-app to the Desktop
# file structure within /my-app is as should be and dependencies are present.
# populates /node_modules/ & /yarn.lock to Desktop as well
```
The installation of `react`, `react-dom`, & `next` seem to **only** be happening in `/Desktop/my-app/node_modules` as the `/Desktop/node_modules` directory & `/Desktop/yarn.lock` are empty. 

Installation was done via:

```sh
yarn global add create-next-app
# upgraded via
yarn global upgrade create-next-app
```

Wondered if it was possibly a `yarn` issue as the `global` keyword has had some issues since `0.23.x` that are set to be resolved with the release of `0.24.0`. Removed & reinstalled using `yarn` & issue persisted, tried `npm install -g create-next-app` to still see the same issue.

I attempted installing using `@0.5.0` & `@0.4.7` but still received the same results.

### Expected behavior

Should only create `node_modules` & `yarn.lock` in `<projectDir>`.

### Environment

Run these commands in the project folder and fill in their results:

1. `create-next-app --version`: **0.5.1**
2. `node --version`: **7.9.0**
3. `npm --version`: **4.5.0**
4. `yarn --version`: **0.23.4**
5. Operating system: **macOS 10.12.4**

**Comment by fouad** [comment]
Hey @rockchalkwushock!

Thanks for reporting this, you're totally right - it shouldn't be adding a `node_modules|yarn.lock` to the "parent" directory. I'll test this evening and try to figure out what's going on.

**Comment by rockchalkwushock** [comment]
@fouad 

If I get some time this weekend I will investigate it more as well. I've never really looked at source code for a CLI tool before so it will be a new experience & those  are always fun 😃

**Comment by rakeshmenon** [comment]
Apparently this issue is only reproducible in the case of yarn. Will look into it and create a PR once I find the resolution.

**Comment by rakeshmenon** [comment]
PR #17 raised for this issue. Was an issue with execa.sync - still exploring cause.

**Comment by rakeshmenon** [comment]
@fouad: This can be closed as well. Same as #19
