### ISSUE TITLE
Duplicate Yarn.lock and node_modules created outside project directory

### ISSUE THREAD

**Issue by nodox** [segmentio/create-next-app#19]
When I create a new project with `create-next-app --example custom-server-express my_app` there are duplicate files that are created outside `/Desktop/my_app` in the `/Desktop` directory.  Needs to be all created in the same directory as `my_app`

**Comment by rakeshmenon** [comment]
@nodox: This is duplicate to #16 for which PR #17 has been created.

**Comment by fouad** [comment]
thanks @nodox for pointing out and rakesh for fixing!
