### ISSUE TITLE
Antd example is missing a package. (transform-decorators-legacy)

### ISSUE THREAD

**Issue by maotora** [segmentio/create-next-app#22]
Hello,

I just installed this package and after a koa example I then ran the Antd which gave me errors when I navigated in my browser to `localhost:3000/`.

It seems `babel-plugin-transform-decorators-legacy` isn't listed in package.json so it's not installed while it's used in `.babelrc`.

So, I think you should add it and stop this error which may mislead others.

**Comment by nilkesede** [comment]
All the examples are fetched directly from the [next.js repository](https://github.com/zeit/next.js/).

**Comment by maotora** [comment]
Oh, good to know.

I was just giving a suggestion too. :)
