### ISSUE TITLE
How do I load Segment?

### ISSUE THREAD

**Issue by JonAbrams** [segmentio/create-next-app#24]
This problem makes me feel awfully silly, but how do I load Segment's JS script in an app created with `create-next-app`? I can't just paste in the script tag snippet since there's no `index.html`.

My current idea to solve this is to make a component that runs the snippet's contents in `componentDidMount`, and to render a hidden dummy div. [Here's what I've whipped up.](https://gist.github.com/JonAbrams/ab7dbb6b28d1603489e1cb3049c7551e)

Note: The component needs to be loaded in the app somewhere other than `<NextHead>`.

Thoughts? Is there a simpler solution? If not, want me to publish a module?

**Comment by JonAbrams** [comment]
I've removed the status logging, since it would get overwritten with each page load.

**Comment by dcurletti** [comment]
Getting an official answer from Segment regarding how to add their JS snippet in a SSR app would be fantastic.

**Comment by stephenmathieson** [comment]
Hey fellas, sorry for the delay! I wasn't watching this repo so I never saw the notification. Fixed that now tho =]

Anyway, what I've done in the past is create a custom document which injects the Segment script. An old example is in my `next.js` fork and can be seen here: https://github.com/stephenmathieson/next.js/blob/add/with-segment-example/examples/with-analytics/pages/_document.js

Hope this helps and feel free to reach out should you have any issues/questions!
