### ISSUE TITLE
'create-next-app --example ...' stuck while 'Downloading files for ... example'

### ISSUE THREAD

**Issue by r0b-** [segmentio/create-next-app#28]
1. `create-next-app --version`: 0.5.2
2. `node --version`: 8.9.3
3. `npm --version`: 5.5.1 or 5.6.0
4. Windows 10

E.g. `create-next-app --example ssr-caching ssr-caching-app` creates two folder 'ssr-caching-app' and '-p' and is stuck on 'Downloading files for ssr-caching example'
I guess the '-p' folder is related to the probem..

Thanks in advance

**Comment by ianisms** [comment]
repro'd on Windows 10

**Comment by cyrus-za** [comment]
Same here. Windows 10. Node 8 npm 5

**Comment by cyrus-za** [comment]
Update: It works for me in git bash

**Comment by stephenmathieson** [comment]
Unfortunately I don't have a Windows machine to test on. I'll try to get a VM setup in the next few days and see what I can find tho

**Comment by renehauck** [comment]
Same here. Ubuntu 16.04. Node v8.9.4 npm 5.6.0

**Comment by cyrus-za** [comment]
Rene it seems to work when using git bash.

**Comment by alikhani** [comment]
Having the same issue macOS 10.13; Node v8.9.0; npm 5.5.1.. 
It says downloading but nothing happens. A folder was created but nothing in it.

**Comment by jackjwilliams** [comment]
Same issue here on Windows 10 in PowerShell

**Comment by SuperFLEB** [comment]
The issue looks to be that the shell commands in `load-example.js` aren't supported by Windows. The `mkdir -p` causes the `-p` directory to be created, and the curl|tar is what it's seizing up on.

**Comment by FadiAboMsalam** [comment]
same issue here , also on windows 7  any updates ?

**Comment by stephenmathieson** [comment]
Hey folks, sorry for the delay here. This is on my radar and I hope to try to get something working for you soon.

**Comment by stephenmathieson** [comment]
I've just opened #40. If anyone is able to verify that it works on their (Windows) system, please do so and let me know!
