### ISSUE TITLE
Document how to add Segment to your Next.js app

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/create-next-app#29]
Since #24 came up, it'd be nice to show users how to easily add Segment to their apps.

**Comment by stephenmathieson** [comment]
You can now use the official [with-analytics example](https://github.com/zeit/next.js/tree/canary/examples/with-analytics).

**Comment by Artforge** [comment]
the link is dead

**Comment by stephenmathieson** [comment]
Here's an updated link: https://github.com/zeit/next.js/tree/canary/examples/with-segment-analytics
