### ISSUE TITLE
[Question] A way to clone a repository instead of using an example?

### ISSUE THREAD

**Issue by johhansantana** [segmentio/create-next-app#32]
Is it possible to use this library to instead of using an example, use a GitHub repository?

**Comment by kevb10** [comment]
Probably not, the repo url is hard coded 
https://github.com/segmentio/create-next-app/blob/master/lib/utils/load-example.js
You can maybe modify that to work for yourself..

**Comment by stephenmathieson** [comment]
No, this is not supported at the moment. If enough folks suggest it, however, it might be something we'll look into tho!
