### ISSUE TITLE
Allow to choose between npm and yarn

### ISSUE THREAD

**Issue by kevb10** [segmentio/create-next-app#39]
Instead of forcing the user to use `yarn` if it is in the path #3 can you at least allow using `npm` without removing `yarn`. For example, `create-react-app` allows you to by having the `--use-npm` option. This would be an awesome feature.

**Comment by JamesSingleton** [comment]
It looks like if you don't have yarn that it uses NPM according to `get-install-cmd.js`
```
const execa = require('execa')

let cmd

module.exports = function getInstallCmd() {
  if (cmd) {
    return cmd
  }

  try {
    execa.shellSync('yarnpkg --version')
    cmd = 'yarn'
  } catch (e) {
    cmd = 'npm'
  }

  return cmd
}
```
