### ISSUE TITLE
enoent ENOENT: no such file or directory, chmod when install

### ISSUE THREAD

**Issue by kazixma** [segmentio/create-next-app#44]
I try to npm install -g create-next-app in windows(10) and ubuntu. It's same error.

> npm ERR! path C:\Users\Admin\AppData\Roaming\npm\node_modules\create-next-app\bin.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\Admin\AppData\Roaming\npm\node_modules\create-next-app\bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-07-26T13_18_20_165Z-debug.log

Ps. I updated npm@latest version 6.2.0 and cache clear.

**Comment by michaelsbradleyjr** [comment]
I'm getting this too, node 8.11.3, npm 6.2.0 and npm 5.6.0.

**Comment by damian87x** [comment]
Same for me on Mac, node 8.11.3, npm 6.1.0

**Comment by younesmln** [comment]
same error here 
```
➜  Desktop npm -v                                                                  
6.2.0
➜  Desktop npm install -g create-next-app                                          
npm ERR! path /Users/myuser/n/lib/node_modules/create-next-app/bin.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/myuser/n/lib/node_modules/create-next-app/bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2018-07-27T12_54_07_635Z-debug.log

```

**Comment by HumeurNoire** [comment]
Issue comes with the 0.5.4 release (@stephenmathieson is the owner)
You can bypass this issue by removing your current version of `create-next-app` by doing a `sudo rm -rf /usr/lib/node_modules/create-next-app` if your are on linux and install the old working version: `sudo npm install -g create-next-app@0.5.3`
Next everything comes back and runs well ;)

**Comment by joynal** [comment]
Fetching the same error, 0.5.3 works for me also.

**Comment by stephenmathieson** [comment]
Just saw this. Fix incoming!

**Comment by stephenmathieson** [comment]
Can install `v0.5.9` now :)

**Comment by concubicycle** [comment]
seeing this on:

npm --version
6.6.0

```
...
65 verbose node v11.6.0
66 verbose npm  v6.6.0
67 error path /usr/lib/node_modules/nsfix/bin/nsfx.js
68 error code ENOENT
69 error errno -2
70 error syscall chmod
71 error enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/nsfix/bin/nsfx.js'
72 error enoent This is related to npm not being able to find a file.
``` 
I checked, the file is there
