### ISSUE TITLE
I want to compress the CSS that I have embedded in the page, and what to do with I want to compress the CSS that I have embedded in the page, and what to do. Less loader

### ISSUE THREAD

**Issue by Weipengzhou** [segmentio/create-next-app#45]
I want to compress the CSS that I have embedded in the page, and what to do with I want to compress the CSS that I have embedded in the page, and what to do. Less loader

**Comment by denisinla** [comment]
Why not use styled-components since you're using a component approach already.

**Comment by stephenmathieson** [comment]
To enable CSS compression, you might have to add a plugin to the webpack config found in `next.config.js`. I agree with @denisinla that you could/should use a "canned" solution (`styled-jsx`, `styled-components`, etc) which would handle this for you.
