### ISSUE TITLE
https://open.segment.com/create-next-app/

### ISSUE THREAD

**Issue by AndrewRayCode** [segmentio/create-next-app#49]
https://open.segment.com/create-next-app/

![screen shot 2018-11-18 at 12 29 50 pm](https://user-images.githubusercontent.com/79215/48677707-af2fc800-eb2d-11e8-88bf-5523d6e2be33.png)

whopz

**Comment by stephenmathieson** [comment]
Whopz indeed. :laughing: 

@nettofarah I don't have access to update tye URL in the repo description, nor do I know what's up with the "open" app. Can you take a look and/or remove the link here?

**Comment by nettofarah** [comment]
Oops.. that doesn't look right.
Tagging @williams-blake

**Comment by fforres** [comment]
Thanks for the @ @nettofarah 🙏 
Oopsie indeed, I'm on it 😄

**Comment by fforres** [comment]
It's aliiiive! :) 

With a minor change. We had to remove the filtering options as api API on now.sh for getting some github metadata got removed.

But we are working on an alternative 🙏,
thanks for the report and conv @AndrewRayCode 	@nettofarah 	@stephenmathieson

> (Will keep the issue open to update)

**Comment by AndrewRayCode** [comment]
~~whopz~~
