### ISSUE TITLE
Npm run dev on different port (other than port :3000)

### ISSUE THREAD

**Issue by stahlmanDesign** [segmentio/create-next-app#50]
Is there an easy way to run the dev server on a port other than 3000?

For example:
`npm run dev -p 3004`

I couldn't find this in the documentation.

**Comment by stephenmathieson** [comment]
Yes, Next.js has a [`--port` or `-p` flag for development mode](https://github.com/zeit/next.js/blob/v7.0.3-alpha.5/packages/next/bin/next-dev#L12).

You can do `$ npm run dev -- --port=3004` (note the additional double-dash `--`).

**Comment by stahlmanDesign** [comment]
Thanks, I tested it and it works with either of these two commands:
`npm run dev -- -p 3004`
`npm run dev -- --port=3004`
