### ISSUE TITLE
Is it normal to get "Client pings, but there's no entry for page :/_error"?

### ISSUE THREAD

**Issue by helloitsm3** [segmentio/create-next-app#59]
![image](https://user-images.githubusercontent.com/13825491/55680878-31405200-5952-11e9-9e65-40515c8cfc65.png)
This is what I'm getting.

**Comment by stephenmathieson** [comment]
No, this is not normal nor expected.

Can you provide steps to reproduce?

**Comment by helloitsm3** [comment]
> No, this is not normal nor expected.
> 
> Can you provide steps to reproduce?

Sorry, I think it was an issue with my computer. It's fixed now.

**Comment by stephenmathieson** [comment]
OK, thanks.

Closing for now.
