### ISSUE TITLE
docs: the components/index.js module is an anitpattern

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/create-next-app#6]
currently, we suggest users import/export all of their components in a single file "index.js". while this does make it _slightly_ easier to import them from pages (you only need 1 import statement to grab many components), it includes components your page won't necessarily need, thus negating next's [built-in code splitting](https://github.com/zeit/next.js/#automatic-code-splitting).

the docs also suggest users should export their components twice (once as a named export, once as a default). i imagine this will confuse people who aren't super familiar with es6 modules. imo we should keep things as simple as possible and drop the named export entirely (assuming we keep the `index.js` file).

would you be open to a pr changing either (or both) of these sections of the documentation?

**Comment by fouad** [comment]
@stephenmathieson that's a great point! I generally prefer it for usability but I think you're right that it should be opt-in via an example. PR would be absolutely welcome!
